conditioning:
  main_sampler: LD-SMC

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: inpainting
  mask_opt:
    mask_type: box
    mask_len_range: !!python/tuple [ 128, 129 ]  # for box
    image_size: 256


  noise:
    name: gaussian
    sigma: 0.01
