conditioning:
  main_sampler: LD-SMC

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 8
  
  noise: 
    name: gaussian
    sigma: 0.01
